name: music-clustering
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |

          # Install requeriments
          pip install -r requirements.txt

          # Pull data
          dvc pull

          # Execute main script
          python ./src/main.py

          echo "# Clustering canciones 2017" >> report.md
          cat ./metadata/experiment.txt >> report.md

          echo "## Cumulative explained variance" >> report.md
          cml-publish ./figures/cumulative_explained_variance.png --md >> report.md

          echo "## Optimal number of clusters - Elbow method" >> report.md
          cml-publish ./figures/elbow_method.png --md >> report.md

          echo "## PCA 2D Scatter plot" >> report.md
          cml-publish ./figures/cluster_pca_2d.png --md >> report.md

          echo "## Polar Subplots - Cluster descriptions" >> report.md
          cml-publish ./figures/single_polar_cluster.png --md >> report.md

          cml-send-comment report.md
