name: music-clustering
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        run: |
          pip install -r requirements.txt
          python ./src/main.py

          echo "## Data Viz" >> report.md
          cml-publish ./figures/cumulative_explained_variance.png --md >> report.md

          cml-send-comment report.md
